server:
  servlet:
    # 应用上下文
    context-path: /spring-boot-thymeleaf
  # 端口号
  port: 8082

spring:
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
